
services:

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${DAPS_DOMAIN}
      - DAPS_PATH=${DAPS_PATH}
    volumes:
      - ${PWD}/nginx/https:/etc/nginx/templates
      - ${DAPS_CERT}:/etc/nginx/daps.cert
      - ${DAPS_KEY}:/etc/nginx/daps.key

  omejdn-server:
    image: ghcr.io/fraunhofer-aisec/omejdn-server:dev
    restart: unless-stopped
    environment:
      - OMEJDN_ISSUER=${DAPS_ISSUER}
      - OMEJDN_FRONT_URL=${DAPS_ISSUER}${DAPS_PATH}
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
    volumes:
      - ${PWD}/config:/opt/config
      - ${PWD}/keys:/opt/keys

