---
plugins:
  claim_mapper:
    attribute:
      skip_access_token: false
      skip_id_token: true
bind_to: 0.0.0.0:4567
environment: development
openid: false
default_audience: idsc:IDS_CONNECTORS_ALL
accept_audience: idsc:IDS_CONNECTORS_ALL
access_token:
  expiration: 3600
  algorithm: RS256
id_token:
  expiration: 3600
  algorithm: RS256
issuer: http://localhost
front_url: http://localhost
